apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-deployment
    labels:
      app: employees
      version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - image: 496056207117.dkr.ecr.us-east-1.amazonaws.com/grp14_webapp:v0.3
        name: webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBHOST
          value: mysql-service.final.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: GROUP14PWD
        - name : DBNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: your_name
        - name: DBIMG 
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: background_image_url
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
