apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30001
  selector:
    app: employees
    version: v1

  
  


