apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
      app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 496056207117.dkr.ecr.us-east-1.amazonaws.com/grp14_db:v0.3
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:           
        - name: data-volume
          mountPath: /var/lib/mysql  
      volumes:               
      - name: data-volume
        persistentVolumeClaim:
          claimName: my-pvc    
  restartPolicy: Always 
            
            
      
