apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /var/lib/mysql